name: binarytf
packagePath: .
commitMessageTemplate: 'chore(release): release {{new-version}}'
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: binarytf/binarytf
gitHostVariant: github
