resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: kyranet

jobs:
  - template: lint.yml@templates
  - job: Build
    pool:
      vmImage: 'ubuntu-16.04'
    dependsOn: Lint
    condition: succeeded()
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: yarn
        displayName: 'Install Dependencies'
      - script: 'yarn build'
        displayName: 'Test Build'
  - job: Test
    pool:
      vmImage: 'ubuntu-16.04'
    dependsOn: Build
    condition: succeeded()
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: yarn
        displayName: 'Install Dependencies'
      - script: 'yarn test'
        displayName: 'Test Suite'
      - script: 'yarn run cover'
        displayName: 'Generate Coverage Results'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
        displayName: 'Publish Coverage Results'
